spring.datasource.url=jdbc:postgresql://dpg-d765em14tr6s73dffgp0-a:5432/usermanagement_xyll
spring.datasource.username=user
spring.datasource.password=vSwuRiiCt7Ce29wFohzZ4ABwN2JGsyxA

spring.sql.init.mode=always


spring.sql.init.data-locations=classpath:/data.sql

spring.sql.init.platform=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
